# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.0
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_version: 14.0
org_name: Akretion
org_slug: akretion
rebel_module_groups: []
repo_description: null
repo_name: Odoo module for improving perfomance
repo_slug: odoo-perf
repo_website: https://github.com/akretion/odoo-perf
travis_apt_packages: []
travis_apt_sources: []

