# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.20
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
convert_readme_fragments_to_markdown: false
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 14.0
org_name: Akretion
org_slug: akretion
rebel_module_groups: []
repo_description: Module for improving odoo perf
repo_name: Odoo module for improving perfomance
repo_slug: odoo-perf
repo_website: https://github.com/akretion/odoo-perf
use_pyproject_toml: false
use_ruff: false

