[project]
name = "odoo-addons-akretion-odoo-perf"
version = "18.0.20260116.0"
dependencies = [
    "odoo-addon-perf_account==18.0.*",
    "odoo-addon-perf_mail==18.0.*",
    "odoo-addon-perf_sale==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
